# serverless.yml

service: sqs-sns-example

provider:
  name: aws
  runtime: nodejs12.x

functions:
  sendMessage:
    handler: sendMessage.handler
    events:
      - sns: dispatch
  receiveMessage:
    handler: receiveMessage.handler
    events:
      - sqs:
          arn:
            "Fn::GetAtt": [myQueue, Arn]

resources:
  Resources:
    myQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: my-sqs-queue
    mySNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: "My SNS Topic"
        TopicName: "my-sns-topic"

plugins:
  - serverless-offline
